# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-03-06 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('margin', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('free_margin', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('equity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('swap_profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('open_lots', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('process_type', models.CharField(choices=[('W', 'Withdraw'), ('D', 'Deposit')], max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='Management.Account')),
            ],
            options={
                'ordering': ('-open_date',),
            },
        ),
        migrations.CreateModel(
            name='Rebalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('enter_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('finish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('period', models.CharField(max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('RQ', 'Request'), ('PR', 'Processing'), ('FS', 'Finish')], max_length=10)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_rebalances', to='Management.Account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_rebalances', to='Management.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Urgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='rebalance',
            name='urgency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebalances', to='Management.Urgency'),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='Management.Currency'),
        ),
    ]
