# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-03-06 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('first_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_pair', to='Management.Account')),
                ('second_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_pair', to='Management.Account')),
            ],
        ),
        migrations.RemoveField(
            model_name='rebalance',
            name='from_account',
        ),
        migrations.RemoveField(
            model_name='rebalance',
            name='to_account',
        ),
        migrations.AddField(
            model_name='rebalance',
            name='direct',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rebalance',
            name='pair',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rebalances', to='Management.AccountPairs'),
            preserve_default=False,
        ),
    ]
