# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-03-11 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='trade_type',
            field=models.CharField(choices=[('FS', 'Forex Swap'), ('FA', 'Forex Arb'), ('GA', 'Gold Arb')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
