# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-03-11 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_client_trade_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpairs',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='Management.Client'),
            preserve_default=False,
        ),
    ]
