# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-03-06 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_auto_20200306_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpairs',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
